### ISSUE TITLE
Respect YouTube `?t=42s` timestamps

### ISSUE THREAD

**Issue by jeysal** [iyzana/vsync#54]
So that the timestamp is saved to the queue along with the entered video, and whenever the video becomes the active one, it plays from that timestamp instead of 0

**Comment by iyzana** [comment]
Fixed in https://github.com/iyzana/vsync/commit/a263165154aa5fff704e22c8e7622f98fb6df9f5 should be live tomorrow

**Comment by jeysal** [comment]
Pog AF
